### ISSUE TITLE
A few examples for the Glossary

### ISSUE THREAD

**Issue by eddiejaoude** [empowerhack/vocapp#1]
To start off with the glossary please can you provide some examples - these do not have to be perfectly accurate, using something like Google Translator is fine for now. This is just to get an understanding of the information

I have started to document the core information to capture, but I will add more after we have some examples https://github.com/empowerhack/vocapp/wiki/Domain

**Comment by oabuamsha** [comment]
Examples:  same word different meanings (so may be adding field?)
##Name: **Abstract**
##Field: Technical writing
##Description: An abstract is a brief summary of a research article, thesis, review, conference proceeding or any in-depth analysis of a particular subject and is often used to help the reader quickly ascertain the paper's purpose.
##source: 
[](https://en.wikipedia.org/wiki/Abstract_(summary)) 
## Languages
### Arabic
ملخص
### Description in Arabic
 موجز مختصر لمقال أو بحث، أو أطروحة، أو محضر مؤتمر أو أي تحليل متعمق لموضوع معين وغالبا ما يستخدم لمساعدة القارئ على التأكد بسرعة من غرض المادة المنشورة.
###Source in Arabic

###French
résumé
### Description in Arabic
un bref résumé d'un article de recherche, d'une thèse, d'actes de conférence ou de tout autre document. Son objectif est de permettre au lecteur de cerner rapidement le sujet du document et ses points principaux.
###source in French:
[](https://fr.wikipedia.org/wiki/R%C3%A9sum%C3%A9_de_th%C3%A8se)

**Comment by eddiejaoude** [comment]
> same word different meanings (so may be adding field?)
Same word, different meaning and different field? Which field would you suggest to add?

**Comment by oabuamsha** [comment]
yes

**Comment by oabuamsha** [comment]
An interesting web dico where you select types of dictionaries to tap in:
[http://www.ldlp-dictionary.com/](http://www.ldlp-dictionary.com/)
