### ISSUE TITLE
field does not show in drop down list unless highlighted

### ISSUE THREAD

**Issue by ghost** [empowerhack/vocapp#111]
![image](https://cloud.githubusercontent.com/assets/20721935/18444501/c2bd3200-7919-11e6-9bc5-f79b69b838dd.png)

**Comment by kevinpmcc** [comment]
eeek, sorry for long delay on this one. 

able to reproduce in firefox on my laptop. will investigate.

**Comment by kevinpmcc** [comment]
Hi, made some changes which I hope has fixed this.

@msafarjalani could you check on your system if this now fixed.

**Comment by ghost** [comment]
Excellent! all good from here. Thanks mate


Malaz SAFARJALANI
*Jamiya | Research, Organisational **Development*
*Development Aid Consultant*

Jamiya news sign-up here <http://eepurl.com/b75s-X>


Brussels, Belgium
+32 471 30 15 40
malaz@jamiya.org
malaz.safar-jalani@coleurope.eu <malaz.safar-jalani@coleurop.eu>

Jamiya Project <http://jamiya.org/> aims to provide higher education for
Syrian refugees, taught by Syrian academics and accredited by European
universities. The Project's model seeks to overcome many of the barriers
facing Syrian students by making courses free, flexible to study and taught
in Arabic.

**Comment by kevinpmcc** [comment]
closing!
