### ISSUE TITLE
Forgot password in signin returns error

### ISSUE THREAD

**Issue by ghost** [empowerhack/vocapp#116]

**Comment by kevinpmcc** [comment]
I'll look into this one today!

**Comment by ghost** [comment]
Cheers Kevin! Lovely of you.

**Comment by kevinpmcc** [comment]
@msafarjalani 
No worries.  Quick question. This requires us to supply an email account to send the forgotten password emails from. 

To test it out  I setup vocappwebsite@gmail.com and forgotten password emails are working  on my local computer. I haven't pushed to heroku (live website) yet. 

Do you want to stick with vocappwebsite@gmail.com or is there another email account I should use?

**Comment by ghost** [comment]
Hi Kevin,
I was trying to set up an account on Jamiya.org domain. But we're hosted on squarespace and we pay for monthly for every new e-mail account. I've been trying to find a way around this.
Though for now I guess it's fine, we might have to change the name of the app at somepoint, since there's already something like this with the same name (it's not that special). So for now let's stick with this arrangement as I will also deploy to jamiya.org if pilot is successful.
Sorry for letting this sleep for a min..

Cheers,
M

**Comment by kevinpmcc** [comment]
No problem at all.

I'll let you know when its integrated into prototype.

**Comment by ghost** [comment]
Hey Keving,
I've made vocapp@jamiya.org feel free to add this instead. Sorry I was
oblivious to some details that I could only get from Ben this afternoon

Cheers,
M

**Comment by kevinpmcc** [comment]
No problem, I've sent a message to you on empowerhack slack about what I think I need to set this up!

**Comment by kevinpmcc** [comment]
set up with vocapp@jamiya.org address and sending reset email links correctly. closing.
