### ISSUE TITLE
Are all languages equal?

### ISSUE THREAD

**Issue by eddiejaoude** [empowerhack/vocapp#2]
Are all languages equal or is English going to be the one parent/owner, eg. always the first one present?

**Comment by benwebster0** [comment]
Not sure what you mean by first one present. What are the implications of either option?

**Comment by eddiejaoude** [comment]
By present, I mean exist.

*For example:* If someone was going to add a new word, would English always be the first to be added, or not always?

**Comment by benwebster0** [comment]
So, that hasn't been decided. But thinking through the logic......ideally, not always: all languages should be equal. It is possible some words in Arabic will have no direct translation into English - they will only have somewhat equivalent words in English. Therefore, the origin of that word - or entry as part of the corpus held - should not be in English. Having said that, I expect this will be a very small number of words and should it be an easier option to develop with English owner, I don't foresee that becoming a significant problem later on....

**Comment by eddiejaoude** [comment]
> some words in Arabic will have no direct translation into English

Good point. 

> expect this will be a very small number of words and should it be an easier option to develop with English owner

Ok thanks. May be for the prototype & simplicity, we can assume English will be put in first, will always exist & will be the owner

**Comment by eddiejaoude** [comment]
E.g.

<img width="281" alt="screenshot 2016-07-13 08 00 29" src="https://cloud.githubusercontent.com/assets/624760/16794497/f599dfb8-48cf-11e6-8795-eeaa76f3a961.png">

**Comment by benwebster0** [comment]
OK. Make sense. Thanks

**Comment by eddiejaoude** [comment]
For the final product, probably should make them all equal & self-referencing, but this adds complexity to everything (e.g. searching).

**Comment by oabuamsha** [comment]
Hi,
I was about to say the contrary!
I I understood well that the dico will be enriched collaboratively, it doesn't have to be English the leading language.
Also, users might be interested in translation between 2 different other languages.
whay not including the language as an attribute for every term?  or creating relations for each language and then create the links between the different entities?

take a look at Linguee.com where you start by selecting the 2 languages you are interested in. this is a good project but no Arabic in the offer..

**Comment by eddiejaoude** [comment]
> why not including the language as an attribute for every term? or creating relations for each language and then create the links between the different entities

Yes, if each term had a language attribute and then it was self-referencing it would be more flexible. For the prototype I was just trying to keep it simple as possible. But if this is important then we should go down this route for the prototype. 

The link is simple enough, but it can have a knock on effects on other functionality. However from the example you provided from **linguee**, if the user is selecting the *source* & *destination* language that keeps things simple again.

**Comment by eddiejaoude** [comment]
<img width="571" alt="screenshot 2016-07-13 08 18 30" src="https://cloud.githubusercontent.com/assets/624760/16794922/6880619e-48d2-11e6-8178-69e7588a1b73.png">

**Comment by oabuamsha** [comment]
meaningful and simple enough
