### ISSUE TITLE
add cucumber testing

### ISSUE THREAD

**Issue by paulalexrees** [empowerhack/vocapp#45]

**Comment by eripheebs** [comment]
do you want cucumber? i think capybara is pretty easy for non-devs to read in this case because we can be v verbose :)

**Comment by eripheebs** [comment]
(plus i already wrote tests in capybara lololol)

**Comment by paulalexrees** [comment]
oh no let's keep capybara for now! one day we'll get better at cucumber (maybe)

**Comment by rhiannonruth** [comment]
Agreed - closing :)
